[target.'cfg(all())']
rustflags = [
   # rustc lints
   "-Wmissing_debug_implementations",
   "-Wnon_camel_case_types",
   "-Wnon_snake_case",
   "-Wnon_upper_case_globals",
   "-Wunused_must_use",
   # clippy lints
   "-Wclippy::approx_constant",
   "-Wclippy::arithmetic_side_effects",
   "-Wclippy::bad_bit_mask",
   "-Wclippy::bool_assert_comparison",
   "-Wclippy::bool_comparison",
   "-Wclippy::borrow_interior_mutable_const",
   "-Wclippy::blocks_in_if_conditions",
   "-Wclippy::declare_interior_mutable_const",
   "-Wclippy::default_numeric_fallback",
   "-Wclippy::derived_hash_with_manual_eq",
   "-Wclippy::derive_ord_xor_partial_ord",
   "-Wclippy::from_over_into",
   "-Wclippy::large_types_passed_by_value",
   "-Wclippy::mut_from_ref",
   "-Wclippy::mutex_atomic",
   "-Wclippy::mutex_integer",
   "-Wclippy::missing_errors_doc",
   "-Wclippy::missing_panics_doc",
   "-Wclippy::missing_safety_doc",
   "-Wclippy::negative_feature_names",
   "-Wclippy::needless_range_loop",
   "-Wclippy::precedence",
   "-Wclippy::recursive_format_impl",
   "-Wclippy::redundant_allocation",
   "-Wclippy::redundant_feature_names",
   "-Wclippy::undocumented_unsafe_blocks",
   "-Wclippy::unwrap_used",
   "-Wclippy::wildcard_imports",
   "-Wclippy::wrong_self_convention",
   # 规范定制 lint 集, 使用官方工具扫描时请注释掉以下 lint
   "-Wclippy::blocking_op_in_async",
   "-Wclippy::dangling_ptr_dereference",
   "-Wclippy::extern_without_repr",
   "-Wclippy::fallible_memory_allocation",
   "-Wclippy::implicit_abi",
   "-Wclippy::invalid_char_range",
   "-Wclippy::infinite_loop",
   "-Wclippy::mem_unsafe_functions",
   "-Wclippy::non_reentrant_functions",
   "-Wclippy::null_ptr_dereference",
   "-Wclippy::passing_string_to_c_functions",
   "-Wclippy::ptr_double_free",
   "-Wclippy::return_stack_address",
   "-Wclippy::unsafe_block_in_proc_macro",
   "-Wclippy::untrusted_lib_loading",
]